name: 'Analytics_Project'
version: '1.0.0'
config-version: 2

profile: 'Analytics_Project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Analytics_Project:
    gold:
      +materialized: table
      +schema: gold
      dimensional:
        +materialized: table
      fact:
        +materialized: table

vars:
  source_schema: 'ZOOM_SILVER_SCHEMA'
  target_schema: 'ZOOM_GOLD_SCHEMA'
