version: 2

sources:
  - name: bronze
    description: "Bronze layer tables from Zoom platform"
    schema: ZOOM_BRONZE_SCHEMA
    tables:
      - name: bz_users
        description: "Bronze layer user data"
        columns:
          - name: email
            description: "User email address"
          - name: user_name
            description: "User display name"
          - name: plan_type
            description: "User subscription plan"
          - name: company
            description: "User company"
            
      - name: bz_meetings
        description: "Bronze layer meeting data"
        columns:
          - name: meeting_topic
            description: "Meeting topic or title"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: end_time
            description: "Meeting end timestamp"
          - name: start_time
            description: "Meeting start timestamp"
            
      - name: bz_licenses
        description: "Bronze layer license data"
        columns:
          - name: license_type
            description: "Type of license"
          - name: end_date
            description: "License expiration date"
          - name: start_date
            description: "License start date"
            
      - name: bz_support_tickets
        description: "Bronze layer support ticket data"
        columns:
          - name: resolution_status
            description: "Ticket resolution status"
          - name: open_date
            description: "Ticket open date"
          - name: ticket_type
            description: "Type of support ticket"
            
      - name: bz_billing_events
        description: "Bronze layer billing event data"
        columns:
          - name: amount
            description: "Billing amount"
          - name: event_type
            description: "Type of billing event"
          - name: event_date
            description: "Billing event date"
            
      - name: bz_participants
        description: "Bronze layer participant data"
        columns:
          - name: leave_time
            description: "Participant leave timestamp"
          - name: join_time
            description: "Participant join timestamp"
            
      - name: bz_webinars
        description: "Bronze layer webinar data"
        columns:
          - name: end_time
            description: "Webinar end timestamp"
          - name: webinar_topic
            description: "Webinar topic or title"
          - name: start_time
            description: "Webinar start timestamp"
          - name: registrants
            description: "Number of webinar registrants"
            
      - name: bz_feature_usage
        description: "Bronze layer feature usage data"
        columns:
          - name: feature_name
            description: "Name of the feature"
          - name: usage_date
            description: "Date of feature usage"
          - name: usage_count
            description: "Number of times feature was used"

models:
  - name: si_audit_log
    description: "Silver layer audit log for tracking processing"
    columns:
      - name: audit_id
        description: "Unique audit record identifier"
        tests:
          - not_null
      - name: process_name
        description: "Name of the process being audited"
        tests:
          - not_null
      - name: source_table
        description: "Source table name"
        tests:
          - not_null
          
  - name: si_meetings
    description: "Silver layer cleaned meeting data"
    columns:
      - name: meeting_id
        description: "Unique meeting identifier"
        tests:
          - unique
          - not_null
      - name: meeting_topic
        description: "Cleaned meeting topic"
        tests:
          - not_null
      - name: duration_minutes
        description: "Validated meeting duration"
        tests:
          - not_null
      - name: start_time
        description: "Meeting start timestamp"
        tests:
          - not_null
      - name: end_time
        description: "Meeting end timestamp"
        tests:
          - not_null
          
  - name: si_users
    description: "Silver layer cleaned user data"
    columns:
      - name: user_id
        description: "Unique user identifier"
        tests:
          - unique
          - not_null
      - name: email
        description: "Validated email address"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Cleaned user name"
        tests:
          - not_null
      - name: plan_type
        description: "Standardized plan type"
        tests:
          - not_null
          
  - name: si_licenses
    description: "Silver layer cleaned license data"
    columns:
      - name: license_id
        description: "Unique license identifier"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Standardized license type"
        tests:
          - not_null
      - name: start_date
        description: "License start date"
        tests:
          - not_null
      - name: end_date
        description: "License end date"
        tests:
          - not_null
