version: 2

sources:
  - name: zoom_raw
    description: "Raw Zoom data from source systems"
    tables:
      - name: meetings
        description: "Raw meetings data from Zoom platform"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: host_id
            description: "Identifier of the meeting host"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Duration of meeting in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: licenses
        description: "Raw license data from Zoom platform"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: support_tickets
        description: "Raw support tickets data from Zoom platform"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
          - name: user_id
            description: "User ID who created the ticket"
          - name: ticket_type
            description: "Type of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: users
        description: "Raw users data from Zoom platform"
        columns:
          - name: user_id
            description: "Unique identifier for each user"
          - name: user_name
            description: "Name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company name of the user"
          - name: plan_type
            description: "Type of plan user is subscribed to"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: billing_events
        description: "Raw billing events data from Zoom platform"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
          - name: user_id
            description: "User ID associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: event_date
            description: "Date of billing event"
          - name: amount
            description: "Amount associated with billing event"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: participants
        description: "Raw participants data from Zoom platform"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant"
          - name: meeting_id
            description: "Meeting ID participant joined"
          - name: user_id
            description: "User ID of the participant"
          - name: join_time
            description: "Timestamp when participant joined"
          - name: leave_time
            description: "Timestamp when participant left"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: webinars
        description: "Raw webinars data from Zoom platform"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
          - name: webinar_topic
            description: "Topic or title of the webinar"
          - name: host_id
            description: "Identifier of the webinar host"
          - name: start_time
            description: "Webinar start timestamp"
          - name: end_time
            description: "Webinar end timestamp"
          - name: registrants
            description: "Number of registrants for webinar"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: feature_usage
        description: "Raw feature usage data from Zoom platform"
        columns:
          - name: usage_id
            description: "Unique identifier for each usage record"
          - name: meeting_id
            description: "Meeting ID where feature was used"
          - name: feature_name
            description: "Name of the feature used"
          - name: usage_date
            description: "Date when feature was used"
          - name: usage_count
            description: "Count of feature usage"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"

models:
  - name: bz_audit_log
    description: "Bronze layer audit log for tracking data processing activities"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for audit records"
        data_type: number
      - name: source_table
        description: "Name of the source table being processed"
        data_type: varchar(255)
      - name: load_timestamp
        description: "Timestamp when processing started"
        data_type: timestamp_ntz
      - name: processed_by
        description: "System or user that processed the data"
        data_type: varchar(100)
      - name: processing_time
        description: "Time taken to process in seconds"
        data_type: number
      - name: status
        description: "Status of the processing (STARTED, COMPLETED, FAILED)"
        data_type: varchar(50)
        
  - name: bz_meetings
    description: "Bronze layer meetings table with 1:1 mapping from raw data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        data_type: string
      - name: meeting_topic
        description: "Topic or title of the meeting"
        data_type: string
      - name: host_id
        description: "Identifier of the meeting host"
        data_type: string
      - name: start_time
        description: "Meeting start timestamp"
        data_type: timestamp_ntz
      - name: end_time
        description: "Meeting end timestamp"
        data_type: timestamp_ntz
      - name: duration_minutes
        description: "Duration of meeting in minutes"
        data_type: number
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
        
  - name: bz_licenses
    description: "Bronze layer licenses table with 1:1 mapping from raw data"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        data_type: string
      - name: license_type
        description: "Type of license"
        data_type: string
      - name: assigned_to_user_id
        description: "User ID to whom license is assigned"
        data_type: string
      - name: start_date
        description: "License start date"
        data_type: date
      - name: end_date
        description: "License end date"
        data_type: date
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
        
  - name: bz_support_tickets
    description: "Bronze layer support tickets table with 1:1 mapping from raw data"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        data_type: string
      - name: user_id
        description: "User ID who created the ticket"
        data_type: string
      - name: ticket_type
        description: "Type of support ticket"
        data_type: string
      - name: resolution_status
        description: "Current status of ticket resolution"
        data_type: string
      - name: open_date
        description: "Date when ticket was opened"
        data_type: date
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
        
  - name: bz_users
    description: "Bronze layer users table with 1:1 mapping from raw data"
    columns:
      - name: user_id
        description: "Unique identifier for each user"
        data_type: string
      - name: user_name
        description: "Name of the user"
        data_type: string
      - name: email
        description: "Email address of the user"
        data_type: string
      - name: company
        description: "Company name of the user"
        data_type: string
      - name: plan_type
        description: "Type of plan user is subscribed to"
        data_type: string
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
        
  - name: bz_billing_events
    description: "Bronze layer billing events table with 1:1 mapping from raw data"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        data_type: string
      - name: user_id
        description: "User ID associated with billing event"
        data_type: string
      - name: event_type
        description: "Type of billing event"
        data_type: string
      - name: event_date
        description: "Date of billing event"
        data_type: date
      - name: amount
        description: "Amount associated with billing event"
        data_type: number
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
        
  - name: bz_participants
    description: "Bronze layer participants table with 1:1 mapping from raw data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant"
        data_type: string
      - name: meeting_id
        description: "Meeting ID participant joined"
        data_type: string
      - name: user_id
        description: "User ID of the participant"
        data_type: string
      - name: join_time
        description: "Timestamp when participant joined"
        data_type: timestamp_ntz
      - name: leave_time
        description: "Timestamp when participant left"
        data_type: timestamp_ntz
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
        
  - name: bz_webinars
    description: "Bronze layer webinars table with 1:1 mapping from raw data"
    columns:
      - name: webinar_id
        description: "Unique identifier for each webinar"
        data_type: string
      - name: webinar_topic
        description: "Topic or title of the webinar"
        data_type: string
      - name: host_id
        description: "Identifier of the webinar host"
        data_type: string
      - name: start_time
        description: "Webinar start timestamp"
        data_type: timestamp_ntz
      - name: end_time
        description: "Webinar end timestamp"
        data_type: timestamp_ntz
      - name: registrants
        description: "Number of registrants for webinar"
        data_type: number
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
        
  - name: bz_feature_usage
    description: "Bronze layer feature usage table with 1:1 mapping from raw data"
    columns:
      - name: usage_id
        description: "Unique identifier for each usage record"
        data_type: string
      - name: meeting_id
        description: "Meeting ID where feature was used"
        data_type: string
      - name: feature_name
        description: "Name of the feature used"
        data_type: string
      - name: usage_date
        description: "Date when feature was used"
        data_type: date
      - name: usage_count
        description: "Count of feature usage"
        data_type: number
      - name: load_timestamp
        description: "Timestamp when record was loaded"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
