version: 2

sources:
  - name: zoom_raw_schema
    description: "Raw data from Zoom platform"
    schema: ZOOM_RAW_SCHEMA
    tables:
      - name: users
        description: "Raw user data from Zoom"
        columns:
          - name: user_id
            description: "Unique identifier for users"
          - name: user_name
            description: "User display name"
          - name: email
            description: "User email address"
          - name: company
            description: "User company"
          - name: plan_type
            description: "Zoom plan type"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"
      
      - name: meetings
        description: "Raw meeting data from Zoom"
        columns:
          - name: meeting_id
            description: "Unique identifier for meetings"
          - name: host_id
            description: "Meeting host user ID"
          - name: meeting_topic
            description: "Meeting topic/title"
          - name: start_time
            description: "Meeting start time"
          - name: end_time
            description: "Meeting end time"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"
      
      - name: participants
        description: "Raw participant data from Zoom"
        columns:
          - name: participant_id
            description: "Unique identifier for participants"
          - name: meeting_id
            description: "Associated meeting ID"
          - name: user_id
            description: "Participant user ID"
          - name: join_time
            description: "Time participant joined"
          - name: leave_time
            description: "Time participant left"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"
      
      - name: feature_usage
        description: "Raw feature usage data from Zoom"
        columns:
          - name: usage_id
            description: "Unique identifier for usage records"
          - name: meeting_id
            description: "Associated meeting ID"
          - name: feature_name
            description: "Name of the feature used"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date of feature usage"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"
      
      - name: webinars
        description: "Raw webinar data from Zoom"
        columns:
          - name: webinar_id
            description: "Unique identifier for webinars"
          - name: host_id
            description: "Webinar host user ID"
          - name: webinar_topic
            description: "Webinar topic/title"
          - name: start_time
            description: "Webinar start time"
          - name: end_time
            description: "Webinar end time"
          - name: registrants
            description: "Number of registrants"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"
      
      - name: support_tickets
        description: "Raw support ticket data from Zoom"
        columns:
          - name: ticket_id
            description: "Unique identifier for support tickets"
          - name: user_id
            description: "User who created the ticket"
          - name: ticket_type
            description: "Type of support ticket"
          - name: resolution_status
            description: "Current resolution status"
          - name: open_date
            description: "Date ticket was opened"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"
      
      - name: licenses
        description: "Raw license data from Zoom"
        columns:
          - name: license_id
            description: "Unique identifier for licenses"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID license is assigned to"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"
      
      - name: billing_events
        description: "Raw billing event data from Zoom"
        columns:
          - name: event_id
            description: "Unique identifier for billing events"
          - name: user_id
            description: "User associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Billing amount"
          - name: event_date
            description: "Date of billing event"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
          - name: source_system
            description: "Source system identifier"

models:
  - name: bz_audit_log
    description: "Audit log for tracking data processing in bronze layer"
    columns:
      - name: record_id
        description: "Auto-incrementing record identifier"
        data_type: number
      - name: source_table
        description: "Name of the source table being processed"
        data_type: varchar(255)
      - name: load_timestamp
        description: "Timestamp when processing started"
        data_type: timestamp_ntz
      - name: processed_by
        description: "System or user that processed the data"
        data_type: varchar(255)
      - name: processing_time
        description: "Time taken to process in seconds"
        data_type: number
      - name: status
        description: "Processing status (STARTED, COMPLETED, FAILED)"
        data_type: varchar(50)
  
  - name: bz_users
    description: "Bronze layer users data with audit information"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        data_type: string
      - name: user_name
        description: "User display name"
        data_type: string
      - name: email
        description: "User email address"
        data_type: string
      - name: company
        description: "User company"
        data_type: string
      - name: plan_type
        description: "Zoom plan type"
        data_type: string
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
  
  - name: bz_meetings
    description: "Bronze layer meetings data with audit information"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        data_type: string
      - name: host_id
        description: "Meeting host user ID"
        data_type: string
      - name: meeting_topic
        description: "Meeting topic/title"
        data_type: string
      - name: start_time
        description: "Meeting start time"
        data_type: timestamp_ntz
      - name: end_time
        description: "Meeting end time"
        data_type: timestamp_ntz
      - name: duration_minutes
        description: "Meeting duration in minutes"
        data_type: number
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
  
  - name: bz_participants
    description: "Bronze layer participants data with audit information"
    columns:
      - name: participant_id
        description: "Unique identifier for participants"
        data_type: string
      - name: meeting_id
        description: "Associated meeting ID"
        data_type: string
      - name: user_id
        description: "Participant user ID"
        data_type: string
      - name: join_time
        description: "Time participant joined"
        data_type: timestamp_ntz
      - name: leave_time
        description: "Time participant left"
        data_type: timestamp_ntz
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
  
  - name: bz_feature_usage
    description: "Bronze layer feature usage data with audit information"
    columns:
      - name: usage_id
        description: "Unique identifier for usage records"
        data_type: string
      - name: meeting_id
        description: "Associated meeting ID"
        data_type: string
      - name: feature_name
        description: "Name of the feature used"
        data_type: string
      - name: usage_count
        description: "Number of times feature was used"
        data_type: number
      - name: usage_date
        description: "Date of feature usage"
        data_type: date
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
  
  - name: bz_webinars
    description: "Bronze layer webinars data with audit information"
    columns:
      - name: webinar_id
        description: "Unique identifier for webinars"
        data_type: string
      - name: host_id
        description: "Webinar host user ID"
        data_type: string
      - name: webinar_topic
        description: "Webinar topic/title"
        data_type: string
      - name: start_time
        description: "Webinar start time"
        data_type: timestamp_ntz
      - name: end_time
        description: "Webinar end time"
        data_type: timestamp_ntz
      - name: registrants
        description: "Number of registrants"
        data_type: number
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
  
  - name: bz_support_tickets
    description: "Bronze layer support tickets data with audit information"
    columns:
      - name: ticket_id
        description: "Unique identifier for support tickets"
        data_type: string
      - name: user_id
        description: "User who created the ticket"
        data_type: string
      - name: ticket_type
        description: "Type of support ticket"
        data_type: string
      - name: resolution_status
        description: "Current resolution status"
        data_type: string
      - name: open_date
        description: "Date ticket was opened"
        data_type: date
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
  
  - name: bz_licenses
    description: "Bronze layer licenses data with audit information"
    columns:
      - name: license_id
        description: "Unique identifier for licenses"
        data_type: string
      - name: license_type
        description: "Type of license"
        data_type: string
      - name: assigned_to_user_id
        description: "User ID license is assigned to"
        data_type: string
      - name: start_date
        description: "License start date"
        data_type: date
      - name: end_date
        description: "License end date"
        data_type: date
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
  
  - name: bz_billing_events
    description: "Bronze layer billing events data with audit information"
    columns:
      - name: event_id
        description: "Unique identifier for billing events"
        data_type: string
      - name: user_id
        description: "User associated with billing event"
        data_type: string
      - name: event_type
        description: "Type of billing event"
        data_type: string
      - name: amount
        description: "Billing amount"
        data_type: number
      - name: event_date
        description: "Date of billing event"
        data_type: date
      - name: load_timestamp
        description: "Bronze layer load timestamp"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Bronze layer update timestamp"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system identifier"
        data_type: string
